In [63]:
import pandas as pd
import matplotlib.pyplot as plt

In [64]:
data = pd.read_csv("../data_sets/Geoscout Facility Data Dump.csv", low_memory=False)

In [65]:
print("Columns in raw data (id, name)")
for idx, name in enumerate(data.columns):
    print(idx, ": ", name, sep="")

Columns in raw data (id, name)
0: Unique Facility ID
1: Status
2: Name
3: Type
4: Plant Name
5: Current Operator
6: Original Operator
7: Co-Owner
8: Constructed Date
9: Activated Date
10: Field Name
11: Latitude
12: Longitude
13: Licensed Capacity of Raw Gas(Mcf/d)
14: Licensed Capacity of Sales Gas(Mcf/d)
15: Licensed Capacity of Oil(Bbl/d)
16: Licensed Capacity of Ethane(C2)(Bbl/d)
17: Licensed Capacity of Ethane Plus(C2+)(Bbl/d)
18: Licensed Capacity of Propane(C3)(Bbl/d)
19: Licensed Capacity of Butane(C4)(Bbl/d)
20: Licensed Capacity of Pentane Plus(C5+)(Bbl/d)
21: Licensed Capacity of NGL(Bbl/d)
22: Licensed Capacity of LPG(Bbl/d)
23: Licensed Capacity of Sulphur(ton/d)
24: Design Capacity of Raw Gas(Mcf/d)
25: Design Capacity of Sales Gas(Mcf/d)
26: Design Capacity of Oil(Bbl/d)
27: Design Capacity of Ethane(C2)(Bbl/d)
28: Design Capacity of Ethane Plus(C2+)(Bbl/d)
29: Design Capacity of Propane(C3)(Bbl/d)
30: Design Capacity of Butane(C4)(Bbl/d)
31: Design Capacity of Pentane Plus(C5+)(Bbl/d)
32: Design Capacity of NGL(Bbl/d)
33: Design Capacity of LPG(Bbl/d)
34: Design Capacity of Sulphur(ton/d)
35: Raw Gas(Mcf/d)
36: Sales Gas(Mcf/d)
37: Ethane(C2)(Bbl/d)
38: Ethane Plus(C2+)(Bbl/d)
39: Propane(C3)(Bbl/d)
40: Butane(C4)(Bbl/d)
41: Pentane Plus(C5+)(Bbl/d)
42: Natural Gas Liquids(Bbl/d)
43: Liquefied Petroleum Gas(Bbl/d)
44: Sulphur(ton/d)
45: Sub Type
46: Location
47: Date
48: Raw Gas(Mcf/d).1
49: Sales Gas(Mcf/d).1
50: Injection(Mcf/d)
51: Shrinkage(Mcf/d)
52: Fuel(Mcf/d)
53: Flared(Mcf/d)
54: Other(Mcf/d)
55: Oil(SK)(Bbl/d)
56: Methane Plus(C1+)(SK)(Bbl/d)
57: Ethane(C2)(Bbl/d).1
58: Ethane Plus(C2+)(Bbl/d).1
59: Propane(C3)(Bbl/d).1
60: Propane Plus(C3+)(SK)(Bbl/d)
61: Butane(C4)(Bbl/d).1
62: Butane Plus(C4+)(SK)(Bbl/d)
63: Pentane(C5)(SK)(Bbl/d)
64: Pentane Plus(C5+)(Bbl/d).1
65: Natural Gas Liquids(Bbl/d).1
66: Sulphur(ton/d).1
67: Receipts of Oil(SK)(Bbl/d)
68: Receipts of Ethane(C2)(SK)(Bbl/d)
69: Receipts of Ethane Plus(C2+)(SK)(Bbl/d)
70: Receipts of Propane(C3)(SK)(Bbl/d)
71: Receipts of Propane Plus(C3+)(SK)(Bbl/d)
72: Receipts of Butane(C4)(SK)(Bbl/d)
73: Receipts of Butane Plus(C4+)(SK)(Bbl/d)
74: Receipts of Pentane(C5)(SK)(Bbl/d)
75: Receipts of Pentane Plus(C5+)(SK)(Bbl/d)
76: Oil Production(Bbl/d)
77: Oil Received(Bbl/d)
78: Oil Open Inventory(Bbl/d)
79: Oil Close Inventory(Bbl/d)
80: Oil Delivered(Bbl/d)
81: Gas Production(Mcf/d)
82: Gas Received(Mcf/d)
83: Lease Fuel(Mcf/d)
84: Gas Flared(Mcf/d)
85: Gas Vented(Mcf/d)
86: Gas Meter Diff(Mcf/d)
87: Gas Delivered(Mcf/d)
88: Water Production(Bbl/d)
89: Water Received(Bbl/d)
90: Water Open Inventory(Bbl/d)
91: Water Close Inventory(Bbl/d)
92: Water Meter Diff(Bbl/d)
93: Water Delivered(Bbl/d)

In [66]:
# Peep into some rows
import random
random_indexes = random.sample(range(0, data.index.size), 10)

data.iloc[random_indexes]

,Unique Facility ID,Status,Name,Type,Plant Name,Current Operator,Original Operator,Co-Owner,Constructed Date,Activated Date,...,Gas Flared(Mcf/d),Gas Vented(Mcf/d),Gas Meter Diff(Mcf/d),Gas Delivered(Mcf/d),Water Production(Bbl/d),Water Received(Bbl/d),Water Open Inventory(Bbl/d),Water Close Inventory(Bbl/d),Water Meter Diff(Bbl/d),Water Delivered(Bbl/d)
199581,ABGP0089914,Active,981405 WEDGE GAS PLANT,GP,Wedge Gas Plant,TALLAHASSEE EXPLORATION INC.,NaN,100.0% - TALLAHASSEE EXPLORATION INC.,1/1/2006,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60661,ABGP0001251,Suspended,CABRE MARTEN HILLS,GP,Fawcett River East,SEQUOIA RESOURCES CORP.,NaN,100.0% - SEQUOIA RESOURCES CORP.,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111693,ABGP0001521,Suspended,GRIMSHAW 11-23-83-23W5,GP,Grimshaw,CANADIAN NATURAL RESOURCES LIMITED,NaN,100.0% - CANAMAX ENERGY LTD.,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166609,ABGP0001795,Suspended,00/16-31-052-21W5 MED LODGE GP,GP,Medicine Lodge,SINOPEC DAYLIGHT ENERGY LTD.,NaN,100.0% - SINOPEC DAYLIGHT ENERGY LTD.,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190483,ABGP0077819,Suspended,CHINCHAGA 10-20-96-7 GP,GP,Chinchaga,KELT EXPLORATION LTD.,NaN,100.0% - KELT EXPLORATION LTD.,1/1/2003,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7344,ABGP0001037,Active,SHELL JUMPING POUND,GP,Jumping Pound,PIERIDAE ALBERTA PRODUCTION LTD.,NaN,100.0% - SHELL CANADA LIMITED,1/1/1951,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165950,ABGP0001791,Active,TRILOGY CLOVER 9-34 PLANT #2,GP,Para Clover Plant 2,PARAMOUNT RESOURCES LTD.,NaN,21.8% - CANADIAN NATURAL RESOURCES LIMITED; 78...,1/1/2001,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151367,ABGP0001693,Active,PENGROWTH MCLEOD,GP,Mcleod,PINE CLIFF ENERGY LTD.,NaN,70.0% - PINE CLIFF ENERGY LTD.,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185675,ABGP0001976,Active,WINDFALL 01-15-062-15W5 GAS PLANT,GP,Sakwatamau,AXIOM OIL AND GAS INC.,NaN,100.0% - AXIOM OIL AND GAS INC.,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78063,ABGP0001343,Active,GOODFARE 04-19-072-11W6 GAS PLANT,GP,Goodfare,TIDEWATER MIDSTREAM AND INFRASTRUCTURE LTD.,NaN,76.1% - CENOVUS ENERGY INC.; 4.8% - SHIELD ENE...,1/1/1979,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
# Skeleton for building the tables

# First column contains the primary key

data.columns = data.columns.str.replace('Unique Facility ID', 'id')

# Facility data
facilities = data.iloc[:, :13].drop_duplicates().reset_index(drop=True)

# Capacity data
facility_capacity = data.iloc[:, [0] + list(range(13, 35))].drop_duplicates().reset_index(drop=True)

# Production data

# I believe this table includes total production, but might need to take a look at it with the next table
facility_total_production = data.iloc[:, [0] + list(range(35, 45))].drop_duplicates().reset_index(drop=True)

# This is MONTHLY production data for that facility by LSD, month, and year, also explains the facility type
facility_monthly_production = data.iloc[:, [0] + list(range(45, 76))].drop_duplicates().reset_index(drop=True)

# Inventory and metering data
facility_inventory_meter = data.iloc[:, [0] + list(range(76, 94))].drop_duplicates().reset_index(drop=True)

# Add all data to a dictionary to loop over it and do high level analysis
data_dict = {
    "facilities": facilities,
    "facility_capacity": facility_capacity,
    "facility_total_production": facility_total_production,
    "facility_monthly_production": facility_monthly_production,
    # "facility_inventory_meter": facility_inventory_meter
}

In [68]:
# Facility inventory and meter looks empty
# We will drop this from our data
# but this needs to be highlighted
facility_inventory_meter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1430 entries, 0 to 1429
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            1430 non-null   object
 1   Oil Production(Bbl/d)         0 non-null      float64
 2   Oil Received(Bbl/d)           0 non-null      float64
 3   Oil Open Inventory(Bbl/d)     0 non-null      float64
 4   Oil Close Inventory(Bbl/d)    0 non-null      float64
 5   Oil Delivered(Bbl/d)          0 non-null      float64
 6   Gas Production(Mcf/d)         0 non-null      float64
 7   Gas Received(Mcf/d)           0 non-null      float64
 8   Lease Fuel(Mcf/d)             0 non-null      float64
 9   Gas Flared(Mcf/d)             0 non-null      float64
 10  Gas Vented(Mcf/d)             0 non-null      float64
 11  Gas Meter Diff(Mcf/d)         0 non-null      float64
 12  Gas Delivered(Mcf/d)          0 non-null      float64
 13  Water Production(Bbl/d)       0 non-null      float64
 14  Water Received(Bbl/d)         0 non-null      float64
 15  Water Open Inventory(Bbl/d)   0 non-null      float64
 16  Water Close Inventory(Bbl/d)  0 non-null      float64
 17  Water Meter Diff(Bbl/d)       0 non-null      float64
 18  Water Delivered(Bbl/d)        0 non-null      float64
dtypes: float64(18), object(1)
memory usage: 212.4+ KB

In [69]:
for name, df in data_dict.items():
    df.columns = df.columns.str.lower().str.replace(' ', '_').str.replace('(', '_').str.replace(')', '')

In [70]:
# Number of rows for each table
for name, df in data_dict.items():
    print(name.replace("_", " ").title(), "# of rows:", df.index.size)

Facilities # of rows: 1430
Facility Capacity # of rows: 1430
Facility Total Production # of rows: 1430
Facility Monthly Production # of rows: 223630

In [71]:
def dms_to_dd(dms):
    """ Parse coordinate data and convert to degrees"""
    if pd.isna(dms):
        return
    degrees, direction = dms.split(' deg ')
    degrees = float(degrees)
    if direction in ['S', 'W']:
        degrees = -degrees
    return degrees

In [72]:
data_dict["facilities"]['latitude']

0       52.14108 deg N
1       52.31571 deg N
2       49.30742 deg N
3       52.75808 deg N
4       52.44144 deg N
             ...
1425    59.20412 deg N
1426    55.79045 deg N
1427               NaN
1428               NaN
1429    56.57191 deg N
Name: latitude, Length: 1430, dtype: object

In [73]:
# Data manipulation
data_dict["facilities"]["latitude"] = data_dict["facilities"]["latitude"].apply(dms_to_dd)
data_dict["facilities"]["longitude"] = data_dict["facilities"]["longitude"].apply(dms_to_dd)

In [74]:
facilities[pd.notna(facilities['activated_date'])].size

0

In [75]:
# Peep into each tables
for name, df in data_dict.items():
    print("Displaying", name)
    display(df.head(10))

Displaying facilities

,id,status,name,type,plant_name,current_operator,original_operator,co-owner,constructed_date,activated_date,field_name,latitude,longitude
0,ABGP0001001,Active,MAPLE GLEN 15-36-036-16W4,GP,Maple Glen,CANADIAN NATURAL RESOURCES LIMITED,NaN,0.0% - CANSEARCH RESOURCES LTD.; 0.0% - CANADI...,NaN,NaN,NaN,52.14108,-112.15671
1,ABGP0001002,Suspended,KEYERA NEVIS GAS PLANT 16-33-38-22W4,GP,Nevis,KEYERA ENERGY LTD.,NaN,100.0% - KEYERA ENERGY LTD.,1/1/1956,NaN,NaN,52.31571,-113.07948
2,ABGP0001003,Suspended,* GULF PINCHER CREEK,GP,Pincher Creek,GULF CANADA LIMITED,NaN,100.0% - PALMER RANCH (1984) LTD.,NaN,NaN,NaN,49.30742,-113.79413
3,ABGP0001004,Active,KEYERA HOMEGLEN-RIMBEY 2-05-44-01W5,GP,Rimbey,KEYERA ENERGY LTD.,NaN,0.0% - CENTIPEDE HOLDINGS LTD.; 0.8% - BELLATR...,1/1/1961,NaN,NaN,52.75808,-114.10751
4,ABGP0001005,Suspended,* GULF GILBY,GP,Gilby,CENOVUS ENERGY INC.,NaN,100.0% - CENOVUS ENERGY INC.,NaN,NaN,NaN,52.44144,-114.30466
5,ABGP0001006,Abandoned,* CHEVRON NEVIS,GP,Nevis,CHEVRON CANADA LIMITED,NaN,100.0% - CHEVRON CANADA LIMITED,NaN,NaN,NaN,52.37406,-113.08470
6,ABGP0001007,Active,MITSUE 16-30-072-04W5,GP,Mitsue,CANADIAN NATURAL RESOURCES LIMITED,NaN,90.0% - CANADIAN NATURAL RESOURCES LIMITED; 10...,1/1/1974,NaN,NaN,55.27045,-114.59501
7,ABGP0001008,Suspended,* CHEVRON PRINCESS,GP,Princess,CHEVRON CANADA LIMITED,NaN,100.0% - CHEVRON CANADA LIMITED,NaN,NaN,NaN,50.68309,-111.54795
8,ABGP0001009,Suspended,SEDALIA 9-29-31-5 GP,GP,Sedalia,BAYTEX ENERGY LTD.,NaN,100.0% - BAYTEX ENERGY LTD.,1/1/1961,NaN,NaN,51.68719,-110.66947
9,ABGP0001010,Suspended,* NORCEN CAMPBELL-NAMAO,GP,Campbell,CANADIAN NATURAL RESOURCES LIMITED,NaN,100.0% - CANADIAN NATURAL RESOURCES LIMITED,NaN,NaN,NaN,53.68898,-113.56889

Displaying facility_capacity

,id,licensed_capacity_of_raw_gas_mcf/d,licensed_capacity_of_sales_gas_mcf/d,licensed_capacity_of_oil_bbl/d,licensed_capacity_of_ethane_c2_bbl/d,licensed_capacity_of_ethane_plus_c2+_bbl/d,licensed_capacity_of_propane_c3_bbl/d,licensed_capacity_of_butane_c4_bbl/d,licensed_capacity_of_pentane_plus_c5+_bbl/d,licensed_capacity_of_ngl_bbl/d,...,design_capacity_of_sales_gas_mcf/d,design_capacity_of_oil_bbl/d,design_capacity_of_ethane_c2_bbl/d,design_capacity_of_ethane_plus_c2+_bbl/d,design_capacity_of_propane_c3_bbl/d,design_capacity_of_butane_c4_bbl/d,design_capacity_of_pentane_plus_c5+_bbl/d,design_capacity_of_ngl_bbl/d,design_capacity_of_lpg_bbl/d,design_capacity_of_sulphur_ton/d
0,ABGP0001001,50111.51,48345.77,NaN,0.00,NaN,0.00,0.00,106.98,NaN,...,9437.84,0.00,0.00,NaN,0.00,0.00,0.00,157.32,NaN,0.00
1,ABGP0001002,150087.32,134301.66,NaN,0.00,NaN,1541.75,1258.57,943.93,NaN,...,110358.32,0.00,0.00,NaN,6292.87,5034.30,3775.72,0.00,NaN,55.12
2,ABGP0001003,89557.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABGP0001004,420880.15,353499.77,NaN,26115.41,0.0,18878.61,10068.59,14247.06,NaN,...,335999.94,12585.74,11956.45,NaN,10188.16,7079.48,14247.06,18123.47,NaN,165.35
4,ABGP0001005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ABGP0001006,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,ABGP0001007,24861.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21188.80,0.00,0.00,NaN,0.00,0.00,0.00,0.00,NaN,0.00
7,ABGP0001008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,ABGP0001009,13984.61,13878.66,NaN,0.00,0.0,0.00,0.00,100.06,NaN,...,8475.52,0.00,0.00,NaN,0.00,0.00,0.00,50.34,NaN,0.00
9,ABGP0001010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Displaying facility_total_production

,id,raw_gas_mcf/d,sales_gas_mcf/d,ethane_c2_bbl/d,ethane_plus_c2+_bbl/d,propane_c3_bbl/d,butane_c4_bbl/d,pentane_plus_c5+_bbl/d,natural_gas_liquids_bbl/d,liquefied_petroleum_gas_bbl/d,sulphur_ton/d
0,ABGP0001001,3952.18,3658.60,0.00,0.0,0.00,0.00,2.62,55.04,NaN,0.00
1,ABGP0001002,64.93,0.00,0.00,0.0,8.36,6.39,0.00,0.00,NaN,0.00
2,ABGP0001003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABGP0001004,206541.92,153997.83,11695.34,0.0,11423.61,7194.45,5212.26,0.00,NaN,9.55
4,ABGP0001005,367268.84,217590.15,0.00,0.0,0.00,0.00,0.00,0.00,NaN,0.00
5,ABGP0001006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,ABGP0001007,3384.67,2940.30,0.00,0.0,0.00,0.00,0.00,119.44,NaN,0.00
7,ABGP0001008,269.07,119.61,0.00,0.0,0.00,0.00,5.81,0.00,NaN,0.00
8,ABGP0001009,1112.75,951.10,0.00,0.0,0.00,0.00,5.70,0.00,NaN,0.00
9,ABGP0001010,10598.96,10576.17,0.00,0.0,0.00,0.00,0.00,0.00,NaN,0.00

Displaying facility_monthly_production

,id,sub_type,location,date,raw_gas_mcf/d.1,sales_gas_mcf/d.1,injection_mcf/d,shrinkage_mcf/d,fuel_mcf/d,flared_mcf/d,...,sulphur_ton/d.1,receipts_of_oil_sk_bbl/d,receipts_of_ethane_c2_sk_bbl/d,receipts_of_ethane_plus_c2+_sk_bbl/d,receipts_of_propane_c3_sk_bbl/d,receipts_of_propane_plus_c3+_sk_bbl/d,receipts_of_butane_c4_sk_bbl/d,receipts_of_butane_plus_c4+_sk_bbl/d,receipts_of_pentane_c5_sk_bbl/d,receipts_of_pentane_plus_c5+_sk_bbl/d
0,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1990/07,27426.39,26439.06,0.0,127.93,344.15,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1990/08,29693.94,28807.77,0.0,143.54,403.84,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1990/09,29129.77,28372.51,0.0,138.08,372.69,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1990/10,22140.02,21020.43,0.0,117.68,293.34,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1990/11,20575.38,19470.62,0.0,87.46,302.18,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1990/12,28591.55,27865.66,0.0,134.42,360.89,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1991/01,27883.09,27292.77,0.0,139.32,385.27,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1991/02,22664.45,22033.32,0.0,122.09,301.81,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1991/03,22589.42,22045.24,0.0,119.50,326.38,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1991/04,23215.98,23004.91,0.0,125.25,249.67,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Quick Data Analysis

In [76]:
num_of_facilities_by_operators = data_dict["facilities"].groupby(['current_operator', 'status']).size().reset_index(name='count')
display(num_of_facilities_by_operators)

          current_operator                 status  count
0     1195714 ALBERTA LTD.                 Active      1
1     1333002 ALBERTA LTD.              Suspended      2
2       177293 CANADA LTD.              Suspended      1
3     2234873 ALBERTA LTD.                 Active      2
4      2349507 CANADA INC.              Suspended      1
..                     ...                    ...    ...
381      XTO ENERGY CANADA                 Active      1
382      XTO ENERGY CANADA              Suspended      1
383  XTO ENERGY CANADA ULC                    New      1
384  ZARGON OIL & GAS LTD.                 Active      1
385  ZARGON OIL & GAS LTD.  Reclamation Certified      1

[386 rows x 3 columns]

In [77]:
# Only look at active facilities
active_facilities_by_operators = num_of_facilities_by_operators.query("status == 'Active'").drop("status", axis=1)
active_facilities_by_operators.rename(columns={'count': 'active_sites'}, inplace=True)

In [78]:
# Top operators in data set
active_facilities_by_operators.sort_values(by="active_sites", ascending=False).head(10)

                                current_operator  active_sites
69            CANADIAN NATURAL RESOURCES LIMITED            80
351                         TOURMALINE OIL CORP.            24
349                           TORXEN ENERGY LTD.            17
27                            ARC RESOURCES LTD.            16
189                           KEYERA ENERGY LTD.            15
346  TIDEWATER MIDSTREAM AND INFRASTRUCTURE LTD.            15
123                         EMBER RESOURCES INC.            13
250                    PEMBINA GAS SERVICES LTD.            11
202                    LONG RUN EXPLORATION LTD.            11
88                           CENOVUS ENERGY INC.            10

In [79]:
num_of_facilities_by_operators.query("current_operator == 'KEYERA ENERGY LTD.'")

       current_operator                 status  count
189  KEYERA ENERGY LTD.                 Active     15
190  KEYERA ENERGY LTD.           Discontinued      1
191  KEYERA ENERGY LTD.  Reclamation Certified      1
192  KEYERA ENERGY LTD.              Suspended      9

In [80]:
# Keyera sites
active_facilities_by_operators.query("current_operator == 'KEYERA ENERGY LTD.'")

       current_operator  active_sites
189  KEYERA ENERGY LTD.            15

In [81]:
facilities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1430 entries, 0 to 1429
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1430 non-null   object
 1   status             1430 non-null   object
 2   name               1295 non-null   object
 3   type               1430 non-null   object
 4   plant_name         1236 non-null   object
 5   current_operator   1297 non-null   object
 6   original_operator  0 non-null      float64
 7   co-owner           1192 non-null   object
 8   constructed_date   606 non-null    object
 9   activated_date     0 non-null      float64
 10  field_name         0 non-null      float64
 11  latitude           1428 non-null   float64
 12  longitude          1428 non-null   float64
dtypes: float64(5), object(8)
memory usage: 145.4+ KB

In [82]:
facilities[facilities['id'] == 'ABGP0001902']

,id,status,name,type,plant_name,current_operator,original_operator,co-owner,constructed_date,activated_date,field_name,latitude,longitude
857,ABGP0001902,Active,EMPRESS GAS PLANT,GP,Empress Straddle Plant,PLAINS MIDSTREAM CANADA ULC,NaN,100.0% - PLAINS MIDSTREAM CANADA ULC,1/1/1971,NaN,NaN,50.67563,-110.02507

In [83]:
# This gets the id for the highest value per column
# Only returns na if there is nothing in that column
max_indices = facility_total_production.idxmax()

for column, idx in max_indices.items():
    if pd.isna(idx) or column == 'id':
        continue

    # Get the index from the facility production table
    facility_id = facility_total_production.iloc[int(idx)].id
    value = facility_total_production.iloc[int(idx)][column]

    # If the max is 0, we skip
    if value == 0.0:
        continue

    # Get the facility name
    facility = facilities.query(f"id == '{facility_id}'")[['name', 'current_operator']]

    name = facility['name'].values[0].title()
    operator = facility['current_operator'].values[0]

    print(f"Highest Facility For {column.replace('_', ' ').title()}: {value:,.2f} at {name}, operated by {operator}")

Highest Facility For Raw Gas Mcf/D: 2,264,493.99 at Empress Gas Plant, operated by PLAINS MIDSTREAM CANADA ULC
Highest Facility For Sales Gas Mcf/D: 2,171,281.53 at Empress Gas Plant, operated by PLAINS MIDSTREAM CANADA ULC
Highest Facility For Ethane C2 Bbl/D: 46,269.46 at Cochrane Extraction Plant, operated by INTER PIPELINE EXTRACTION LTD.
Highest Facility For Propane C3 Bbl/D: 20,800.03 at Pembina Infra. & Logistics Lp Frac 1, operated by PEMBINA NGL CORPORATION
Highest Facility For Butane C4 Bbl/D: 14,866.21 at Keyera Fort Sask Frac Plant, operated by KEYERA ENERGY LTD.
Highest Facility For Pentane Plus C5+ Bbl/D: 16,461.56 at Keyera Pipestone 04-07 Gas Plant, operated by KEYERA ENERGY LTD.
Highest Facility For Natural Gas Liquids Bbl/D: 32,583.14 at Cochrane Extraction Plant, operated by INTER PIPELINE EXTRACTION LTD.
Highest Facility For Sulphur Ton/D: 990.87 at Sukunka Pine River C-085-D/093-P-12 001, operated by SUKUNKA NATURAL RESOURCES INC.

C:\Users\gusta\AppData\Local\Temp\ipykernel_35808\768721683.py:3: FutureWarning: The behavior of DataFrame.idxmax with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  max_indices = facility_total_production.idxmax()

## Data Clean Before Export

In [84]:
facilities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1430 entries, 0 to 1429
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1430 non-null   object
 1   status             1430 non-null   object
 2   name               1295 non-null   object
 3   type               1430 non-null   object
 4   plant_name         1236 non-null   object
 5   current_operator   1297 non-null   object
 6   original_operator  0 non-null      float64
 7   co-owner           1192 non-null   object
 8   constructed_date   606 non-null    object
 9   activated_date     0 non-null      float64
 10  field_name         0 non-null      float64
 11  latitude           1428 non-null   float64
 12  longitude          1428 non-null   float64
dtypes: float64(5), object(8)
memory usage: 145.4+ KB

In [94]:
facility.dropna(axis=1, how='all', inplace=True)
facility_capacity.dropna(axis=1, how='all', inplace=True)
facility_total_production.dropna(axis=1, how='all', inplace=True)
facility_monthly_production.dropna(axis=1, how='all', inplace=True)

In [86]:
facility_monthly_production.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 223630 entries, 0 to 223629
Data columns (total 32 columns):
 #   Column                                 Non-Null Count   Dtype
---  ------                                 --------------   -----
 0   id                                     223630 non-null  object
 1   sub_type                               212861 non-null  object
 2   location                               223628 non-null  object
 3   date                                   223348 non-null  object
 4   raw_gas_mcf/d.1                        223348 non-null  float64
 5   sales_gas_mcf/d.1                      223348 non-null  float64
 6   injection_mcf/d                        223348 non-null  float64
 7   shrinkage_mcf/d                        223348 non-null  float64
 8   fuel_mcf/d                             223348 non-null  float64
 9   flared_mcf/d                           223348 non-null  float64
 10  other_mcf/d                            223348 non-null  float64
 11  oil_sk_bbl/d                           223348 non-null  float64
 12  methane_plus_c1+_sk_bbl/d              223348 non-null  float64
 13  ethane_c2_bbl/d.1                      223348 non-null  float64
 14  ethane_plus_c2+_bbl/d.1                223348 non-null  float64
 15  propane_c3_bbl/d.1                     223348 non-null  float64
 16  propane_plus_c3+_sk_bbl/d              223348 non-null  float64
 17  butane_c4_bbl/d.1                      223348 non-null  float64
 18  butane_plus_c4+_sk_bbl/d               223348 non-null  float64
 19  pentane_c5_sk_bbl/d                    223348 non-null  float64
 20  pentane_plus_c5+_bbl/d.1               223348 non-null  float64
 21  natural_gas_liquids_bbl/d.1            223348 non-null  float64
 22  sulphur_ton/d.1                        223348 non-null  float64
 23  receipts_of_oil_sk_bbl/d               223348 non-null  float64
 24  receipts_of_ethane_c2_sk_bbl/d         223348 non-null  float64
 25  receipts_of_ethane_plus_c2+_sk_bbl/d   223348 non-null  float64
 26  receipts_of_propane_c3_sk_bbl/d        223348 non-null  float64
 27  receipts_of_propane_plus_c3+_sk_bbl/d  223348 non-null  float64
 28  receipts_of_butane_c4_sk_bbl/d         223348 non-null  float64
 29  receipts_of_butane_plus_c4+_sk_bbl/d   223348 non-null  float64
 30  receipts_of_pentane_c5_sk_bbl/d        223348 non-null  float64
 31  receipts_of_pentane_plus_c5+_sk_bbl/d  223348 non-null  float64
dtypes: float64(28), object(4)
memory usage: 54.6+ MB

In [87]:
for c in facility_total_production.columns:
    if facility_total_production[c].sum() == 0.0:
        print(c, "only has 0 values")
        print(f"Dropping {c}...")
        facility_total_production.drop(c, axis=1, inplace=True)
        print(f"{c} has been removed from the dataset")
        print("\n")

ethane_plus_c2+_bbl/d only has 0 values
Dropping ethane_plus_c2+_bbl/d...
ethane_plus_c2+_bbl/d has been removed from the dataset

In [88]:
for c in facility_monthly_production.columns[4:]:
    if facility_monthly_production[c].sum() == 0.0:
        print(c, "only has 0 values")
        print(f"Dropping {c}...")
        facility_monthly_production.drop(c, axis=1, inplace=True)
        print(f"{c} has been removed from the dataset")
        print("\n")

oil_sk_bbl/d only has 0 values
Dropping oil_sk_bbl/d...
oil_sk_bbl/d has been removed from the dataset


methane_plus_c1+_sk_bbl/d only has 0 values
Dropping methane_plus_c1+_sk_bbl/d...
methane_plus_c1+_sk_bbl/d has been removed from the dataset


ethane_plus_c2+_bbl/d.1 only has 0 values
Dropping ethane_plus_c2+_bbl/d.1...
ethane_plus_c2+_bbl/d.1 has been removed from the dataset


propane_plus_c3+_sk_bbl/d only has 0 values
Dropping propane_plus_c3+_sk_bbl/d...
propane_plus_c3+_sk_bbl/d has been removed from the dataset


butane_plus_c4+_sk_bbl/d only has 0 values
Dropping butane_plus_c4+_sk_bbl/d...
butane_plus_c4+_sk_bbl/d has been removed from the dataset


pentane_c5_sk_bbl/d only has 0 values
Dropping pentane_c5_sk_bbl/d...
pentane_c5_sk_bbl/d has been removed from the dataset


receipts_of_oil_sk_bbl/d only has 0 values
Dropping receipts_of_oil_sk_bbl/d...
receipts_of_oil_sk_bbl/d has been removed from the dataset


receipts_of_ethane_c2_sk_bbl/d only has 0 values
Dropping receipts_of_ethane_c2_sk_bbl/d...
receipts_of_ethane_c2_sk_bbl/d has been removed from the dataset


receipts_of_ethane_plus_c2+_sk_bbl/d only has 0 values
Dropping receipts_of_ethane_plus_c2+_sk_bbl/d...
receipts_of_ethane_plus_c2+_sk_bbl/d has been removed from the dataset


receipts_of_propane_c3_sk_bbl/d only has 0 values
Dropping receipts_of_propane_c3_sk_bbl/d...
receipts_of_propane_c3_sk_bbl/d has been removed from the dataset


receipts_of_propane_plus_c3+_sk_bbl/d only has 0 values
Dropping receipts_of_propane_plus_c3+_sk_bbl/d...
receipts_of_propane_plus_c3+_sk_bbl/d has been removed from the dataset


receipts_of_butane_c4_sk_bbl/d only has 0 values
Dropping receipts_of_butane_c4_sk_bbl/d...
receipts_of_butane_c4_sk_bbl/d has been removed from the dataset


receipts_of_butane_plus_c4+_sk_bbl/d only has 0 values
Dropping receipts_of_butane_plus_c4+_sk_bbl/d...
receipts_of_butane_plus_c4+_sk_bbl/d has been removed from the dataset


receipts_of_pentane_c5_sk_bbl/d only has 0 values
Dropping receipts_of_pentane_c5_sk_bbl/d...
receipts_of_pentane_c5_sk_bbl/d has been removed from the dataset


receipts_of_pentane_plus_c5+_sk_bbl/d only has 0 values
Dropping receipts_of_pentane_plus_c5+_sk_bbl/d...
receipts_of_pentane_plus_c5+_sk_bbl/d has been removed from the dataset

In [95]:
# Title case the operator name to match the other file
facilities['current_operator'] = facilities['current_operator'].str.title()
facilities['co-owner'] = facilities['co-owner'].str.title()

# Parse dates
facilities['constructed_date'] = pd.to_datetime(facilities['constructed_date'], format='%m/%d/%Y')
facility_monthly_production['date'] = pd.to_datetime(facility_monthly_production['date'], format='%Y/%m')

In [96]:
facilities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1430 entries, 0 to 1429
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 1430 non-null   object
 1   status             1430 non-null   object
 2   name               1295 non-null   object
 3   type               1430 non-null   object
 4   plant_name         1236 non-null   object
 5   current_operator   1297 non-null   object
 6   original_operator  0 non-null      float64
 7   co-owner           1192 non-null   object
 8   constructed_date   606 non-null    datetime64[ns]
 9   activated_date     0 non-null      float64
 10  field_name         0 non-null      float64
 11  latitude           1428 non-null   float64
 12  longitude          1428 non-null   float64
dtypes: datetime64[ns](1), float64(5), object(7)
memory usage: 145.4+ KB

In [93]:
# Peep into each tables
for name, df in data_dict.items():
    print("Displaying", name)
    display(df.head(10))

Displaying facilities

,id,status,name,type,plant_name,current_operator,original_operator,co-owner,constructed_date,activated_date,field_name,latitude,longitude
0,ABGP0001001,Active,MAPLE GLEN 15-36-036-16W4,GP,Maple Glen,Canadian Natural Resources Limited,NaN,0.0% - Cansearch Resources Ltd.; 0.0% - Canadi...,NaT,NaN,NaN,52.14108,-112.15671
1,ABGP0001002,Suspended,KEYERA NEVIS GAS PLANT 16-33-38-22W4,GP,Nevis,Keyera Energy Ltd.,NaN,100.0% - Keyera Energy Ltd.,1956-01-01,NaN,NaN,52.31571,-113.07948
2,ABGP0001003,Suspended,* GULF PINCHER CREEK,GP,Pincher Creek,Gulf Canada Limited,NaN,100.0% - Palmer Ranch (1984) Ltd.,NaT,NaN,NaN,49.30742,-113.79413
3,ABGP0001004,Active,KEYERA HOMEGLEN-RIMBEY 2-05-44-01W5,GP,Rimbey,Keyera Energy Ltd.,NaN,0.0% - Centipede Holdings Ltd.; 0.8% - Bellatr...,1961-01-01,NaN,NaN,52.75808,-114.10751
4,ABGP0001005,Suspended,* GULF GILBY,GP,Gilby,Cenovus Energy Inc.,NaN,100.0% - Cenovus Energy Inc.,NaT,NaN,NaN,52.44144,-114.30466
5,ABGP0001006,Abandoned,* CHEVRON NEVIS,GP,Nevis,Chevron Canada Limited,NaN,100.0% - Chevron Canada Limited,NaT,NaN,NaN,52.37406,-113.08470
6,ABGP0001007,Active,MITSUE 16-30-072-04W5,GP,Mitsue,Canadian Natural Resources Limited,NaN,90.0% - Canadian Natural Resources Limited; 10...,1974-01-01,NaN,NaN,55.27045,-114.59501
7,ABGP0001008,Suspended,* CHEVRON PRINCESS,GP,Princess,Chevron Canada Limited,NaN,100.0% - Chevron Canada Limited,NaT,NaN,NaN,50.68309,-111.54795
8,ABGP0001009,Suspended,SEDALIA 9-29-31-5 GP,GP,Sedalia,Baytex Energy Ltd.,NaN,100.0% - Baytex Energy Ltd.,1961-01-01,NaN,NaN,51.68719,-110.66947
9,ABGP0001010,Suspended,* NORCEN CAMPBELL-NAMAO,GP,Campbell,Canadian Natural Resources Limited,NaN,100.0% - Canadian Natural Resources Limited,NaT,NaN,NaN,53.68898,-113.56889

Displaying facility_capacity

,id,licensed_capacity_of_raw_gas_mcf/d,licensed_capacity_of_sales_gas_mcf/d,licensed_capacity_of_ethane_c2_bbl/d,licensed_capacity_of_ethane_plus_c2+_bbl/d,licensed_capacity_of_propane_c3_bbl/d,licensed_capacity_of_butane_c4_bbl/d,licensed_capacity_of_pentane_plus_c5+_bbl/d,licensed_capacity_of_ngl_bbl/d,licensed_capacity_of_lpg_bbl/d,licensed_capacity_of_sulphur_ton/d,design_capacity_of_raw_gas_mcf/d,design_capacity_of_sales_gas_mcf/d,design_capacity_of_oil_bbl/d,design_capacity_of_ethane_c2_bbl/d,design_capacity_of_propane_c3_bbl/d,design_capacity_of_butane_c4_bbl/d,design_capacity_of_pentane_plus_c5+_bbl/d,design_capacity_of_ngl_bbl/d,design_capacity_of_sulphur_ton/d
0,ABGP0001001,50111.51,48345.77,0.00,NaN,0.00,0.00,106.98,NaN,1171.1,0.00,10432.30,9437.84,0.00,0.00,0.00,0.00,0.00,157.32,0.00
1,ABGP0001002,150087.32,134301.66,0.00,NaN,1541.75,1258.57,943.93,NaN,NaN,52.86,149381.02,110358.32,0.00,0.00,6292.87,5034.30,3775.72,0.00,55.12
2,ABGP0001003,89557.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABGP0001004,420880.15,353499.77,26115.41,0.0,18878.61,10068.59,14247.06,NaN,0.0,52.86,400000.00,335999.94,12585.74,11956.45,10188.16,7079.48,14247.06,18123.47,165.35
4,ABGP0001005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ABGP0001006,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,ABGP0001007,24861.52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21188.80,21188.80,0.00,0.00,0.00,0.00,0.00,0.00,0.00
7,ABGP0001008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,ABGP0001009,13984.61,13878.66,0.00,0.0,0.00,0.00,100.06,NaN,0.0,0.00,8475.52,8475.52,0.00,0.00,0.00,0.00,0.00,50.34,0.00
9,ABGP0001010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Displaying facility_total_production

,id,raw_gas_mcf/d,sales_gas_mcf/d,ethane_c2_bbl/d,propane_c3_bbl/d,butane_c4_bbl/d,pentane_plus_c5+_bbl/d,natural_gas_liquids_bbl/d,sulphur_ton/d
0,ABGP0001001,3952.18,3658.60,0.00,0.00,0.00,2.62,55.04,0.00
1,ABGP0001002,64.93,0.00,0.00,8.36,6.39,0.00,0.00,0.00
2,ABGP0001003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABGP0001004,206541.92,153997.83,11695.34,11423.61,7194.45,5212.26,0.00,9.55
4,ABGP0001005,367268.84,217590.15,0.00,0.00,0.00,0.00,0.00,0.00
5,ABGP0001006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,ABGP0001007,3384.67,2940.30,0.00,0.00,0.00,0.00,119.44,0.00
7,ABGP0001008,269.07,119.61,0.00,0.00,0.00,5.81,0.00,0.00
8,ABGP0001009,1112.75,951.10,0.00,0.00,0.00,5.70,0.00,0.00
9,ABGP0001010,10598.96,10576.17,0.00,0.00,0.00,0.00,0.00,0.00

Displaying facility_monthly_production

,id,sub_type,location,date,raw_gas_mcf/d.1,sales_gas_mcf/d.1,injection_mcf/d,shrinkage_mcf/d,fuel_mcf/d,flared_mcf/d,other_mcf/d,ethane_c2_bbl/d.1,propane_c3_bbl/d.1,butane_c4_bbl/d.1,pentane_plus_c5+_bbl/d.1,natural_gas_liquids_bbl/d.1,sulphur_ton/d.1
0,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1990-07-01,27426.39,26439.06,0.0,127.93,344.15,0.0,515.25,0.0,0.0,0.0,0.0,0.0,0.0
1,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1990-08-01,29693.94,28807.77,0.0,143.54,403.84,0.0,338.79,0.0,0.0,0.0,0.0,0.0,0.0
2,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1990-09-01,29129.77,28372.51,0.0,138.08,372.69,0.0,246.50,0.0,0.0,0.0,0.0,0.0,0.0
3,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1990-10-01,22140.02,21020.43,0.0,117.68,293.34,0.0,708.57,0.0,0.0,0.0,0.0,0.0,0.0
4,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1990-11-01,20575.38,19470.62,0.0,87.46,302.18,0.0,715.12,0.0,0.0,0.0,0.0,0.0,0.0
5,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1990-12-01,28591.55,27865.66,0.0,134.42,360.89,0.0,230.57,0.0,0.0,0.0,0.0,0.0,0.0
6,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1991-01-01,27883.09,27292.77,0.0,139.32,385.27,0.0,65.73,0.0,0.0,0.0,0.0,0.0,0.0
7,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1991-02-01,22664.45,22033.32,0.0,122.09,301.81,0.0,207.22,0.0,0.0,0.0,0.0,0.0,0.0
8,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1991-03-01,22589.42,22045.24,0.0,119.50,326.38,0.0,98.31,0.0,0.0,0.0,0.0,0.0,0.0
9,ABGP0001001,Gas Plant Sweet,15-36-036-16W4M,1991-04-01,23215.98,23004.91,0.0,125.25,249.67,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0

In [92]:
import os

if not os.path.exists("data_cleaned"):
    os.mkdir("data_cleaned")

facilities.to_csv("data_cleaned/facilities.csv")
facility_capacity.to_csv("data_cleaned/facility_capacity.csv")
facility_total_production.to_csv("data_cleaned/facility_total_production.csv")
facility_monthly_production.to_csv("data_cleaned/facility_monthly_production.csv")